# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 99f11c0993b5937a34cf42475f82561bf64cec464529a34e29a9bc9d9d5436b3ad5f067448e8b0b68d4802cf0cb614845a85aff250b949d34a1200f9ea406de9

test:
  secret_key_base: 0893622ca37b8df5171f4c37729b2d156fe71bd0243121b7a8555c6a2540a0dd6828ae83a3965629c69b8b5d1ced074597dbc8539be53943e615094f65092437

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
